discord = 'your discord token here'
# Discord bot token. DO NOT SHARE THIS WITH ANYONE!
# You can get this from https://discordapp.com/developers/applications
hetzner = 'your hetzner token here'
# Hetzner Cloud API token. DO NOT SHARE THIS WITH ANYONE (EVEN MORE SO THAN THE DISCORD ONE)!
# You can get this from https://console.hetzner.com/projects/ in the Security tab.
cloudflare = 'your clouflare token here'
# Cloudlfare API token.  DO NOT SHARE THIS WITH ANYONE (EVEN MORE SO THAN THE DISCORD ONE)!
# You can get this from https://console.hetzner.com/projects/ in the Security tab.