dev_guild_id = 111111111111111
# The ID of the guild with access to the override commands
domain = "example.com"
# The domain to subdomain for the servers.
cloudflare_zone_id = ""
# The cloudlfare zone ID of the aforementioned domain.
ipv4_cost = 0.0008
# Hetzner's Cost per hour for IPv4.
[shutdown]
lookahead = 10
# Minutes to shut down before the next billing hour if empty/no credits.
lookbehind = 5
# Minutes to take into consideration for activity BEFORE shutdow lookahead start.