"""change_floats_to_bigint

Revision ID: 5e01b22ec412
Revises: baseline_init
Create Date: 2026-06-12 16:53:15.696899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5e01b22ec412'
down_revision: Union[str, Sequence[str], None] = 'baseline_init'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE servers SET credits = CAST(ROUND(credits * 100000) AS INTEGER)")
    op.execute("UPDATE servers SET snapshot_reserve = CAST(ROUND(snapshot_reserve * 100000) AS INTEGER)")
    op.execute("UPDATE servers SET cost_per_hour = CAST(ROUND(cost_per_hour * 100000) AS INTEGER)")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('credits', existing_type=sa.FLOAT(), type_=sa.BigInteger(), existing_nullable=False)
        batch_op.alter_column('snapshot_reserve',
                              existing_type=sa.FLOAT(),
                              type_=sa.BigInteger(),
                              existing_nullable=False)
        batch_op.alter_column('cost_per_hour', existing_type=sa.FLOAT(), type_=sa.BigInteger(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('cost_per_hour', existing_type=sa.BigInteger(), type_=sa.FLOAT(), existing_nullable=False)
        batch_op.alter_column('snapshot_reserve',
                              existing_type=sa.BigInteger(),
                              type_=sa.FLOAT(),
                              existing_nullable=False)
        batch_op.alter_column('credits', existing_type=sa.BigInteger(), type_=sa.FLOAT(), existing_nullable=False)
    # ### end Alembic commands ###
    op.execute("UPDATE servers SET credits = credits / 100000.0")
    op.execute("UPDATE servers SET snapshot_reserve = snapshot_reserve / 100000.0")
    op.execute("UPDATE servers SET cost_per_hour = cost_per_hour / 100000.0")
