"""baseline

Revision ID: baseline_init
Revises: 
Create Date: 2026-06-12 16:51:55.275301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'baseline_init'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'servers', sa.Column('id', sa.UUID(), nullable=False), sa.Column('name', sa.String(), nullable=False),
        sa.Column('discord_id', sa.BigInteger(), nullable=False), sa.Column('role_id', sa.BigInteger(), nullable=True),
        sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
        sa.Column('hcloud_server_id', sa.BigInteger(), nullable=True),
        sa.Column('current_snapshot_id', sa.BigInteger(), nullable=False),
        sa.Column('status',
                  sa.Enum('OFFLINE', 'ONLINE', 'SNAPSHOTTING', 'DELETING', 'PROVISIONING', 'STARTING', name='status'),
                  nullable=False), sa.Column('server_type', sa.String(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True), sa.Column('credits', sa.Float(), nullable=False),
        sa.Column('snapshot_reserve', sa.Float(), nullable=False), sa.Column('cost_per_hour',
                                                                             sa.Float(),
                                                                             nullable=False),
        sa.Column('stop_requested', sa.Boolean(), nullable=False), sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('a2s_port', sa.Integer(), nullable=False), sa.Column('cloudflare_zone_id', sa.String(),
                                                                       nullable=True),
        sa.Column('cloudflare_record_id', sa.String(), nullable=True), sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'))
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_discord_id'), ['discord_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_discord_id'))

    op.drop_table('servers')
    # ### end Alembic commands ###
