"""Introduce Snapshot Billing

Revision ID: 2f2b1a37829f
Revises: 5e01b22ec412
Create Date: 2026-06-13 03:35:13.050668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2f2b1a37829f'
down_revision: Union[str, Sequence[str], None] = '5e01b22ec412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_size', sa.BigInteger(), nullable=False, server_default="1000000"))
        batch_op.add_column(sa.Column('notified_7d', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('notified_24h', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('notified_24h')
        batch_op.drop_column('notified_7d')
        batch_op.drop_column('snapshot_size')

    # ### end Alembic commands ###
